version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    restart: unless-stopped
    command: python -m chainlit run app/app.py -w --host 0.0.0.0 --port 7860