from pydantic import BaseModel, model_validator, Field
from typing import Dict, Self, Optional, Any, List
import ulid

class ChatRequest(BaseModel):
    session_id: str = ""
    message: str
    model_params: Optional[Dict[str, Any]] = None

    @model_validator(mode="after")
    def set_session_id(self) -> Self:
        if not self.session_id:
            self.session_id = ulid.ulid()
        return self


# --- Branch Listing ---
class BranchListResponse(BaseModel):
    branches: List[str] = Field(..., description="List of branch names in the repository.")


# --- Valid Target Branches ---
class ValidTargetBranchesRequest(BaseModel):
    session_id: str = Field(..., description="Session identifier.")
    repo: str = Field(..., description="Repository name.")
    source_branch: str = Field(..., description="Source branch name.")

class ValidTargetBranchesResponse(BaseModel):
    valid_target_branches: List[str] = Field(..., description="List of valid target branch names.")


# --- Pull Request Creation ---
class CreatePullRequestRequest(BaseModel):
    session_id: str = Field(..., description="Session identifier.")
    repo: str = Field(..., description="Repository name.")
    source_branch: str = Field(..., description="Source branch name.")
    target_branch: str = Field(..., description="Target branch name.")
    title: Optional[str] = Field(None, description="Title of the pull request.")
    # If description is not provided, it will be generated by LLM from commit messages
    description: Optional[str] = Field(None, description="Description/body of the pull request.")
    draft: Optional[bool] = Field(False, description="Whether to create the PR as a draft.")
    reviewers: Optional[List[str]] = Field(None, description="List of reviewer usernames.")
    assignees: Optional[List[str]] = Field(None, description="List of assignee usernames.")
    labels: Optional[List[str]] = Field(None, description="List of label names.")

class CreatePullRequestResponse(BaseModel):
    url: str = Field(..., description="URL of the created pull request.")
    number: int = Field(..., description="Pull request number.")
    state: str = Field(..., description="State of the pull request (e.g., open, closed).")
    success: bool = Field(..., description="Whether the pull request was created successfully.")
    # Optionally, include the generated description if LLM was used
    generated_description: Optional[str] = Field(None, description="LLM-generated PR description, if applicable.")


# --- Utility: Commit List for PR Description Generation ---
class CommitMessagesForPRDescriptionRequest(BaseModel):
    commit_messages: List[str] = Field(..., description="List of commit messages to summarize.")
    session_id: str = Field(..., description="Session identifier.")

class PRDescriptionResponse(BaseModel):
    description: str = Field(..., description="LLM-generated pull request description.")