name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/git-recap/package-lock.json

    - name: Install dependencies
      working-directory: app/git-recap
      run: npm ci

    - name: Build
      working-directory: app/git-recap
      run: npm run build --if-present

    - name: Test
      working-directory: app/git-recap
      run: npm test

    - name: Deploy with gh-pages
      working-directory: app/git-recap
      run: |
        git remote set-url origin https://git:${GIT_TOKEN}@github.com/${GIT_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
