name: Sync docs to GitHub Wiki
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GITHUB_TOKEN to push

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Checkout Wiki repo into docs/tmp-wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GITHUB_TOKEN }}  # Safe and works within same repo
          path: docs/tmp-wiki

      - name: Move .git from wiki clone to docs folder
        run: |
          cd docs
          mv tmp-wiki/.git ./
          rm -rf tmp-wiki

      - name: Commit and push to Wiki
        run: |
          cd docs
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync app/docs to GitHub Wiki" || echo "No changes to commit"
          git push origin master
