name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/publish-wiki.yml
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
